version: '3.8'

services:
  zomboid-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-zomboid
    restart: unless-stopped
    environment:
      - UPDATE_SERVER=false 
      - ADMINPASSWORD=pzpass
      - DefaultPort=12345
    ports:
      - "16261:16261/udp"
      - "8766:8766/udp"
      - "16262-16272:16262-16272/udp"
    volumes:
          - zomboid-data:/home/pzuser/Zomboid
          - zomboid-server:/home/pzuser/pzserver
    stdin_open: true
    stop_grace_period: 30s

volumes:
  zomboid-data:
  zomboid-server:
